filebeat.inputs:
  - type: filestream
    id: {{ component }}
    enabled: true
    paths:
      - {{ log_file }}
    fields:
      component: {{ component }}

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.31.79.77:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ================================== Logging ===================================
