labels:
  - { tag: Name, label: name }
  - { tag: env, label: env }
  - { tag: component, label: component }

components:
  - { name: cart, Service_name: cart }
  - { name: catalogue, Service_name: catalogue }
  - { name: user, Service_name: user }
  - { name: shipping, Service_name: shipping }
  - { name: payment, Service_name: payment }
  - { name: frontend, Service_name: nginx }